var annotated_dup =
[
    [ "OmniSketch", "namespace_omni_sketch.html", [
      [ "Data", "namespace_omni_sketch_1_1_data.html", [
        [ "Record", "struct_omni_sketch_1_1_data_1_1_record.html", "struct_omni_sketch_1_1_data_1_1_record" ],
        [ "DataFormat", "class_omni_sketch_1_1_data_1_1_data_format.html", "class_omni_sketch_1_1_data_1_1_data_format" ],
        [ "StreamData", "class_omni_sketch_1_1_data_1_1_stream_data.html", "class_omni_sketch_1_1_data_1_1_stream_data" ],
        [ "GndTruth", "class_omni_sketch_1_1_data_1_1_gnd_truth.html", "class_omni_sketch_1_1_data_1_1_gnd_truth" ],
        [ "Estimation", "class_omni_sketch_1_1_data_1_1_estimation.html", "class_omni_sketch_1_1_data_1_1_estimation" ]
      ] ],
      [ "Hash", "namespace_omni_sketch_1_1_hash.html", [
        [ "HashBase", "class_omni_sketch_1_1_hash_1_1_hash_base.html", "class_omni_sketch_1_1_hash_1_1_hash_base" ],
        [ "AwareHash", "class_omni_sketch_1_1_hash_1_1_aware_hash.html", "class_omni_sketch_1_1_hash_1_1_aware_hash" ]
      ] ],
      [ "Sketch", "namespace_omni_sketch_1_1_sketch.html", [
        [ "CounterHierarchy", "class_omni_sketch_1_1_sketch_1_1_counter_hierarchy.html", "class_omni_sketch_1_1_sketch_1_1_counter_hierarchy" ],
        [ "SketchBase", "class_omni_sketch_1_1_sketch_1_1_sketch_base.html", "class_omni_sketch_1_1_sketch_1_1_sketch_base" ],
        [ "hash_table_elem", "class_omni_sketch_1_1_sketch_1_1hash__table__elem.html", "class_omni_sketch_1_1_sketch_1_1hash__table__elem" ],
        [ "bucket_list_elem", "class_omni_sketch_1_1_sketch_1_1bucket__list__elem.html", "class_omni_sketch_1_1_sketch_1_1bucket__list__elem" ],
        [ "StreamSummary", "class_omni_sketch_1_1_sketch_1_1_stream_summary.html", "class_omni_sketch_1_1_sketch_1_1_stream_summary" ],
        [ "BloomFilter", "class_omni_sketch_1_1_sketch_1_1_bloom_filter.html", "class_omni_sketch_1_1_sketch_1_1_bloom_filter" ],
        [ "CHCMSketch", "class_omni_sketch_1_1_sketch_1_1_c_h_c_m_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_c_m_sketch" ],
        [ "CHCountingBloomFilter", "class_omni_sketch_1_1_sketch_1_1_c_h_counting_bloom_filter.html", "class_omni_sketch_1_1_sketch_1_1_c_h_counting_bloom_filter" ],
        [ "CHCountSketch", "class_omni_sketch_1_1_sketch_1_1_c_h_count_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_count_sketch" ],
        [ "CHCUSketch", "class_omni_sketch_1_1_sketch_1_1_c_h_c_u_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_c_u_sketch" ],
        [ "CHDeltoid", "class_omni_sketch_1_1_sketch_1_1_c_h_deltoid.html", "class_omni_sketch_1_1_sketch_1_1_c_h_deltoid" ],
        [ "CHDeltoid2Tuple", "class_omni_sketch_1_1_sketch_1_1_c_h_deltoid2_tuple.html", "class_omni_sketch_1_1_sketch_1_1_c_h_deltoid2_tuple" ],
        [ "CHElasticSketch", "class_omni_sketch_1_1_sketch_1_1_c_h_elastic_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_elastic_sketch" ],
        [ "CHFlowRadar", "class_omni_sketch_1_1_sketch_1_1_c_h_flow_radar.html", "class_omni_sketch_1_1_sketch_1_1_c_h_flow_radar" ],
        [ "CHHashPipe", "class_omni_sketch_1_1_sketch_1_1_c_h_hash_pipe.html", "class_omni_sketch_1_1_sketch_1_1_c_h_hash_pipe" ],
        [ "CHHeavyKeeper", "class_omni_sketch_1_1_sketch_1_1_c_h_heavy_keeper.html", "class_omni_sketch_1_1_sketch_1_1_c_h_heavy_keeper" ],
        [ "CHHHUnivMon", "class_omni_sketch_1_1_sketch_1_1_c_h_h_h_univ_mon.html", "class_omni_sketch_1_1_sketch_1_1_c_h_h_h_univ_mon" ],
        [ "CHMVSketch", "class_omni_sketch_1_1_sketch_1_1_c_h_m_v_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_m_v_sketch" ],
        [ "CHNitroSketch", "class_omni_sketch_1_1_sketch_1_1_c_h_nitro_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_nitro_sketch" ],
        [ "CHNZESketch", "class_omni_sketch_1_1_sketch_1_1_c_h_n_z_e_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_n_z_e_sketch" ],
        [ "CHPRSketch", "class_omni_sketch_1_1_sketch_1_1_c_h_p_r_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_p_r_sketch" ],
        [ "CHQueryingCountingBloomFilter", "class_omni_sketch_1_1_sketch_1_1_c_h_querying_counting_bloom_filter.html", "class_omni_sketch_1_1_sketch_1_1_c_h_querying_counting_bloom_filter" ],
        [ "CHSketchLearn", "class_omni_sketch_1_1_sketch_1_1_c_h_sketch_learn.html", "class_omni_sketch_1_1_sketch_1_1_c_h_sketch_learn" ],
        [ "CHSketchLearn2Tuple", "class_omni_sketch_1_1_sketch_1_1_c_h_sketch_learn2_tuple.html", "class_omni_sketch_1_1_sketch_1_1_c_h_sketch_learn2_tuple" ],
        [ "CHUnivMon", "class_omni_sketch_1_1_sketch_1_1_c_h_univ_mon.html", "class_omni_sketch_1_1_sketch_1_1_c_h_univ_mon" ],
        [ "CHWavingSketch", "class_omni_sketch_1_1_sketch_1_1_c_h_waving_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_h_waving_sketch" ],
        [ "CMSketch", "class_omni_sketch_1_1_sketch_1_1_c_m_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_m_sketch" ],
        [ "CounterBraids", "class_omni_sketch_1_1_sketch_1_1_counter_braids.html", "class_omni_sketch_1_1_sketch_1_1_counter_braids" ],
        [ "CounterTree", "class_omni_sketch_1_1_sketch_1_1_counter_tree.html", "class_omni_sketch_1_1_sketch_1_1_counter_tree" ],
        [ "CountingBloomFilter", "class_omni_sketch_1_1_sketch_1_1_counting_bloom_filter.html", "class_omni_sketch_1_1_sketch_1_1_counting_bloom_filter" ],
        [ "CountSketch", "class_omni_sketch_1_1_sketch_1_1_count_sketch.html", "class_omni_sketch_1_1_sketch_1_1_count_sketch" ],
        [ "CUSketch", "class_omni_sketch_1_1_sketch_1_1_c_u_sketch.html", "class_omni_sketch_1_1_sketch_1_1_c_u_sketch" ],
        [ "Deltoid", "class_omni_sketch_1_1_sketch_1_1_deltoid.html", "class_omni_sketch_1_1_sketch_1_1_deltoid" ],
        [ "Deltoid2Tuple", "class_omni_sketch_1_1_sketch_1_1_deltoid2_tuple.html", "class_omni_sketch_1_1_sketch_1_1_deltoid2_tuple" ],
        [ "DHSketch", "class_omni_sketch_1_1_sketch_1_1_d_h_sketch.html", "class_omni_sketch_1_1_sketch_1_1_d_h_sketch" ],
        [ "DHSNode", "class_omni_sketch_1_1_sketch_1_1_d_h_s_node.html", "class_omni_sketch_1_1_sketch_1_1_d_h_s_node" ],
        [ "ElasticSketch", "class_omni_sketch_1_1_sketch_1_1_elastic_sketch.html", "class_omni_sketch_1_1_sketch_1_1_elastic_sketch" ],
        [ "FlowRadar", "class_omni_sketch_1_1_sketch_1_1_flow_radar.html", "class_omni_sketch_1_1_sketch_1_1_flow_radar" ],
        [ "HashPipe", "class_omni_sketch_1_1_sketch_1_1_hash_pipe.html", "class_omni_sketch_1_1_sketch_1_1_hash_pipe" ],
        [ "HeavyKeeper", "class_omni_sketch_1_1_sketch_1_1_heavy_keeper.html", "class_omni_sketch_1_1_sketch_1_1_heavy_keeper" ],
        [ "HHUnivMon", "class_omni_sketch_1_1_sketch_1_1_h_h_univ_mon.html", "class_omni_sketch_1_1_sketch_1_1_h_h_univ_mon" ],
        [ "LDSketch", "class_omni_sketch_1_1_sketch_1_1_l_d_sketch.html", "class_omni_sketch_1_1_sketch_1_1_l_d_sketch" ],
        [ "MVSketch", "class_omni_sketch_1_1_sketch_1_1_m_v_sketch.html", "class_omni_sketch_1_1_sketch_1_1_m_v_sketch" ],
        [ "NitroSketch", "class_omni_sketch_1_1_sketch_1_1_nitro_sketch.html", "class_omni_sketch_1_1_sketch_1_1_nitro_sketch" ],
        [ "NZESketch", "class_omni_sketch_1_1_sketch_1_1_n_z_e_sketch.html", "class_omni_sketch_1_1_sketch_1_1_n_z_e_sketch" ],
        [ "PCMSketch", "class_omni_sketch_1_1_sketch_1_1_p_c_m_sketch.html", "class_omni_sketch_1_1_sketch_1_1_p_c_m_sketch" ],
        [ "PCUSketch", "class_omni_sketch_1_1_sketch_1_1_p_c_u_sketch.html", "class_omni_sketch_1_1_sketch_1_1_p_c_u_sketch" ],
        [ "PRSketch", "class_omni_sketch_1_1_sketch_1_1_p_r_sketch.html", "class_omni_sketch_1_1_sketch_1_1_p_r_sketch" ],
        [ "QueryingCountingBloomFilter", "class_omni_sketch_1_1_sketch_1_1_querying_counting_bloom_filter.html", "class_omni_sketch_1_1_sketch_1_1_querying_counting_bloom_filter" ],
        [ "SALSACM", "class_omni_sketch_1_1_sketch_1_1_s_a_l_s_a_c_m.html", "class_omni_sketch_1_1_sketch_1_1_s_a_l_s_a_c_m" ],
        [ "SALSACU", "class_omni_sketch_1_1_sketch_1_1_s_a_l_s_a_c_u.html", "class_omni_sketch_1_1_sketch_1_1_s_a_l_s_a_c_u" ],
        [ "SketchLearn", "class_omni_sketch_1_1_sketch_1_1_sketch_learn.html", "class_omni_sketch_1_1_sketch_1_1_sketch_learn" ],
        [ "SketchLearn2Tuple", "class_omni_sketch_1_1_sketch_1_1_sketch_learn2_tuple.html", "class_omni_sketch_1_1_sketch_1_1_sketch_learn2_tuple" ],
        [ "THD_CHCMSketch", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_c_m_sketch.html", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_c_m_sketch" ],
        [ "THD_CHCountSketch", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_count_sketch.html", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_count_sketch" ],
        [ "THD_CHDeltoid", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_deltoid.html", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_deltoid" ],
        [ "THD_CHFlowRadar", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_flow_radar.html", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_flow_radar" ],
        [ "THD_CHHHUnivMon", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_h_h_univ_mon.html", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_h_h_univ_mon" ],
        [ "THD_CHNitroSketch", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_nitro_sketch.html", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_nitro_sketch" ],
        [ "THD_CHSketchLearn", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_sketch_learn.html", "class_omni_sketch_1_1_sketch_1_1_t_h_d___c_h_sketch_learn" ],
        [ "UnivMon", "class_omni_sketch_1_1_sketch_1_1_univ_mon.html", "class_omni_sketch_1_1_sketch_1_1_univ_mon" ],
        [ "WavingSketch", "class_omni_sketch_1_1_sketch_1_1_waving_sketch.html", "class_omni_sketch_1_1_sketch_1_1_waving_sketch" ]
      ] ],
      [ "Test", "namespace_omni_sketch_1_1_test.html", [
        [ "MetricVec", "class_omni_sketch_1_1_test_1_1_metric_vec.html", "class_omni_sketch_1_1_test_1_1_metric_vec" ],
        [ "TestBase", "class_omni_sketch_1_1_test_1_1_test_base.html", "class_omni_sketch_1_1_test_1_1_test_base" ],
        [ "BloomFilterTest", "class_omni_sketch_1_1_test_1_1_bloom_filter_test.html", "class_omni_sketch_1_1_test_1_1_bloom_filter_test" ],
        [ "CHCMSketchTest", "class_omni_sketch_1_1_test_1_1_c_h_c_m_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_c_m_sketch_test" ],
        [ "CHCountingBloomFilterTest", "class_omni_sketch_1_1_test_1_1_c_h_counting_bloom_filter_test.html", "class_omni_sketch_1_1_test_1_1_c_h_counting_bloom_filter_test" ],
        [ "CHCountSketchTest", "class_omni_sketch_1_1_test_1_1_c_h_count_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_count_sketch_test" ],
        [ "CHCUSketchTest", "class_omni_sketch_1_1_test_1_1_c_h_c_u_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_c_u_sketch_test" ],
        [ "CHDeltoid2TupleTest", "class_omni_sketch_1_1_test_1_1_c_h_deltoid2_tuple_test.html", "class_omni_sketch_1_1_test_1_1_c_h_deltoid2_tuple_test" ],
        [ "CHDeltoidTest", "class_omni_sketch_1_1_test_1_1_c_h_deltoid_test.html", "class_omni_sketch_1_1_test_1_1_c_h_deltoid_test" ],
        [ "CHElasticSketchTest", "class_omni_sketch_1_1_test_1_1_c_h_elastic_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_elastic_sketch_test" ],
        [ "CHFlowRadarTest", "class_omni_sketch_1_1_test_1_1_c_h_flow_radar_test.html", "class_omni_sketch_1_1_test_1_1_c_h_flow_radar_test" ],
        [ "CHHashPipeTest", "class_omni_sketch_1_1_test_1_1_c_h_hash_pipe_test.html", "class_omni_sketch_1_1_test_1_1_c_h_hash_pipe_test" ],
        [ "CHHeavyKeeperTest", "class_omni_sketch_1_1_test_1_1_c_h_heavy_keeper_test.html", "class_omni_sketch_1_1_test_1_1_c_h_heavy_keeper_test" ],
        [ "CHHHUnivMonTest", "class_omni_sketch_1_1_test_1_1_c_h_h_h_univ_mon_test.html", "class_omni_sketch_1_1_test_1_1_c_h_h_h_univ_mon_test" ],
        [ "CHMVSketchTest", "class_omni_sketch_1_1_test_1_1_c_h_m_v_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_m_v_sketch_test" ],
        [ "CHNitroSketchTest", "class_omni_sketch_1_1_test_1_1_c_h_nitro_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_nitro_sketch_test" ],
        [ "CHNZESketchTest", "class_omni_sketch_1_1_test_1_1_c_h_n_z_e_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_n_z_e_sketch_test" ],
        [ "CHPRSketchTest", "class_omni_sketch_1_1_test_1_1_c_h_p_r_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_p_r_sketch_test" ],
        [ "CHQueryingCountingBloomFilterTest", "class_omni_sketch_1_1_test_1_1_c_h_querying_counting_bloom_filter_test.html", "class_omni_sketch_1_1_test_1_1_c_h_querying_counting_bloom_filter_test" ],
        [ "CHSketchLearn2TupleTest", "class_omni_sketch_1_1_test_1_1_c_h_sketch_learn2_tuple_test.html", "class_omni_sketch_1_1_test_1_1_c_h_sketch_learn2_tuple_test" ],
        [ "CHSketchLearnTest", "class_omni_sketch_1_1_test_1_1_c_h_sketch_learn_test.html", "class_omni_sketch_1_1_test_1_1_c_h_sketch_learn_test" ],
        [ "CHUnivMonTest", "class_omni_sketch_1_1_test_1_1_c_h_univ_mon_test.html", "class_omni_sketch_1_1_test_1_1_c_h_univ_mon_test" ],
        [ "CHWavingSketchTest", "class_omni_sketch_1_1_test_1_1_c_h_waving_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_h_waving_sketch_test" ],
        [ "CMSketchTest", "class_omni_sketch_1_1_test_1_1_c_m_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_m_sketch_test" ],
        [ "CounterBraidsTest", "class_omni_sketch_1_1_test_1_1_counter_braids_test.html", "class_omni_sketch_1_1_test_1_1_counter_braids_test" ],
        [ "CounterTreeTest", "class_omni_sketch_1_1_test_1_1_counter_tree_test.html", "class_omni_sketch_1_1_test_1_1_counter_tree_test" ],
        [ "CountingBloomFilterTest", "class_omni_sketch_1_1_test_1_1_counting_bloom_filter_test.html", "class_omni_sketch_1_1_test_1_1_counting_bloom_filter_test" ],
        [ "CountSketchTest", "class_omni_sketch_1_1_test_1_1_count_sketch_test.html", "class_omni_sketch_1_1_test_1_1_count_sketch_test" ],
        [ "CUSketchTest", "class_omni_sketch_1_1_test_1_1_c_u_sketch_test.html", "class_omni_sketch_1_1_test_1_1_c_u_sketch_test" ],
        [ "Deltoid2TupleTest", "class_omni_sketch_1_1_test_1_1_deltoid2_tuple_test.html", "class_omni_sketch_1_1_test_1_1_deltoid2_tuple_test" ],
        [ "DeltoidTest", "class_omni_sketch_1_1_test_1_1_deltoid_test.html", "class_omni_sketch_1_1_test_1_1_deltoid_test" ],
        [ "DHSketchTest", "class_omni_sketch_1_1_test_1_1_d_h_sketch_test.html", "class_omni_sketch_1_1_test_1_1_d_h_sketch_test" ],
        [ "ElasticSketchTest", "class_omni_sketch_1_1_test_1_1_elastic_sketch_test.html", "class_omni_sketch_1_1_test_1_1_elastic_sketch_test" ],
        [ "FlowRadarTest", "class_omni_sketch_1_1_test_1_1_flow_radar_test.html", "class_omni_sketch_1_1_test_1_1_flow_radar_test" ],
        [ "HashPipeTest", "class_omni_sketch_1_1_test_1_1_hash_pipe_test.html", "class_omni_sketch_1_1_test_1_1_hash_pipe_test" ],
        [ "HeavyKeeperTest", "class_omni_sketch_1_1_test_1_1_heavy_keeper_test.html", "class_omni_sketch_1_1_test_1_1_heavy_keeper_test" ],
        [ "HHUnivMonTest", "class_omni_sketch_1_1_test_1_1_h_h_univ_mon_test.html", "class_omni_sketch_1_1_test_1_1_h_h_univ_mon_test" ],
        [ "LDSketchTest", "class_omni_sketch_1_1_test_1_1_l_d_sketch_test.html", "class_omni_sketch_1_1_test_1_1_l_d_sketch_test" ],
        [ "MVSketchTest", "class_omni_sketch_1_1_test_1_1_m_v_sketch_test.html", "class_omni_sketch_1_1_test_1_1_m_v_sketch_test" ],
        [ "NitroSketchTest", "class_omni_sketch_1_1_test_1_1_nitro_sketch_test.html", "class_omni_sketch_1_1_test_1_1_nitro_sketch_test" ],
        [ "NZESketchTest", "class_omni_sketch_1_1_test_1_1_n_z_e_sketch_test.html", "class_omni_sketch_1_1_test_1_1_n_z_e_sketch_test" ],
        [ "PCMSketchTest", "class_omni_sketch_1_1_test_1_1_p_c_m_sketch_test.html", "class_omni_sketch_1_1_test_1_1_p_c_m_sketch_test" ],
        [ "PCUSketchTest", "class_omni_sketch_1_1_test_1_1_p_c_u_sketch_test.html", "class_omni_sketch_1_1_test_1_1_p_c_u_sketch_test" ],
        [ "PRSketchTest", "class_omni_sketch_1_1_test_1_1_p_r_sketch_test.html", "class_omni_sketch_1_1_test_1_1_p_r_sketch_test" ],
        [ "QueryingCountingBloomFilterTest", "class_omni_sketch_1_1_test_1_1_querying_counting_bloom_filter_test.html", "class_omni_sketch_1_1_test_1_1_querying_counting_bloom_filter_test" ],
        [ "SALSACMTest", "class_omni_sketch_1_1_test_1_1_s_a_l_s_a_c_m_test.html", "class_omni_sketch_1_1_test_1_1_s_a_l_s_a_c_m_test" ],
        [ "SALSACUTest", "class_omni_sketch_1_1_test_1_1_s_a_l_s_a_c_u_test.html", "class_omni_sketch_1_1_test_1_1_s_a_l_s_a_c_u_test" ],
        [ "SketchLearn2TupleTest", "class_omni_sketch_1_1_test_1_1_sketch_learn2_tuple_test.html", "class_omni_sketch_1_1_test_1_1_sketch_learn2_tuple_test" ],
        [ "SketchLearnTest", "class_omni_sketch_1_1_test_1_1_sketch_learn_test.html", "class_omni_sketch_1_1_test_1_1_sketch_learn_test" ],
        [ "THD_CHCMSketchTest", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_c_m_sketch_test.html", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_c_m_sketch_test" ],
        [ "THD_CHCountSketchTest", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_count_sketch_test.html", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_count_sketch_test" ],
        [ "THD_CHDeltoidTest", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_deltoid_test.html", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_deltoid_test" ],
        [ "THD_CHFlowRadarTest", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_flow_radar_test.html", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_flow_radar_test" ],
        [ "THD_CHHHUnivMonTest", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_h_h_univ_mon_test.html", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_h_h_univ_mon_test" ],
        [ "THD_CHNitroSketchTest", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_nitro_sketch_test.html", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_nitro_sketch_test" ],
        [ "THD_CHSketchLearnTest", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_sketch_learn_test.html", "class_omni_sketch_1_1_test_1_1_t_h_d___c_h_sketch_learn_test" ],
        [ "UnivMonTest", "class_omni_sketch_1_1_test_1_1_univ_mon_test.html", "class_omni_sketch_1_1_test_1_1_univ_mon_test" ],
        [ "WavingSketchTest", "class_omni_sketch_1_1_test_1_1_waving_sketch_test.html", "class_omni_sketch_1_1_test_1_1_waving_sketch_test" ]
      ] ],
      [ "Util", "namespace_omni_sketch_1_1_util.html", [
        [ "ConfigParser", "class_omni_sketch_1_1_util_1_1_config_parser.html", "class_omni_sketch_1_1_util_1_1_config_parser" ],
        [ "DynamicIntX", "class_omni_sketch_1_1_util_1_1_dynamic_int_x.html", "class_omni_sketch_1_1_util_1_1_dynamic_int_x" ],
        [ "PcapParser", "class_omni_sketch_1_1_util_1_1_pcap_parser.html", "class_omni_sketch_1_1_util_1_1_pcap_parser" ]
      ] ],
      [ "FlowKeyOutOfRange", "class_omni_sketch_1_1_flow_key_out_of_range.html", "class_omni_sketch_1_1_flow_key_out_of_range" ],
      [ "FlowKeyMismtach", "class_omni_sketch_1_1_flow_key_mismtach.html", "class_omni_sketch_1_1_flow_key_mismtach" ],
      [ "FlowKey", "class_omni_sketch_1_1_flow_key.html", "class_omni_sketch_1_1_flow_key" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< OmniSketch::FlowKey< key_len > >", "structstd_1_1hash_3_01_omni_sketch_1_1_flow_key_3_01key__len_01_4_01_4.html", "structstd_1_1hash_3_01_omni_sketch_1_1_flow_key_3_01key__len_01_4_01_4" ],
      [ "equal_to< OmniSketch::FlowKey< key_len > >", "structstd_1_1equal__to_3_01_omni_sketch_1_1_flow_key_3_01key__len_01_4_01_4.html", "structstd_1_1equal__to_3_01_omni_sketch_1_1_flow_key_3_01key__len_01_4_01_4" ]
    ] ],
    [ "MySketch", "class_my_sketch.html", "class_my_sketch" ]
];